# Generated by Django 3.1.1 on 2022-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220318_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petphoto',
            old_name='publication_date',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='petphoto',
            name='user',
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
