# Generated by Django 3.1.1 on 2022-03-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
