# Generated by Django 4.0.1 on 2022-01-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('first_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_trait', to='champions.trait')),
                ('second_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_trait', to='champions.trait')),
                ('third_trait', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_trait', to='champions.trait')),
            ],
        ),
    ]
