# Generated by Django 4.0.1 on 2022-01-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_trait_effect_alter_champion_third_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='ability',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trait',
            name='effect',
            field=models.TextField(max_length=150),
        ),
    ]
