# Generated by Django 4.0.1 on 2022-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0003_champion_ability_alter_trait_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
