# Generated by Django 4.0.2 on 2022-02-23 21:01

from django.db import migrations, models
import expenses_tracker_exam_prep.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[expenses_tracker_exam_prep.web.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
